ARG IMAGE_NAME="debian:bullseye-20230411"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME
# FROM debian:bullseye-20230411

ENV THIS_IMAGE=${IMAGE_NAME}


# Configurar repositorios históricos de Debian 11
RUN echo 'deb http://archive.debian.org/debian bullseye main' > /etc/apt/sources.list && \
	apt-get -o Acquire::Check-Valid-Until=false update && \
	apt-get -o Acquire::Check-Valid-Until=false install -y \
	figlet \
	neofetch \
	mc && \
	rm -rf /var/lib/apt/lists/*

# Copiar entrypoint
COPY entrypoint.01.sh /usr/local/bin/entrypoint.sh

# Configurar prompt, alias y permisos
RUN echo "\nPS1='{ \033[01;33m\]debian:bullseye-20230411\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] $ '" >> /root/.bashrc && \
	echo "alias ls='ls --color=auto' \nalias ll='ls -alF' \nalias lk='ls -l'" >> /root/.bashrc && \
	chmod +x /usr/local/bin/entrypoint.sh



# Define el comando de entrada predeterminado
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Define el comando predeterminado si no se proporciona ninguno al iniciar el contenedor
# Este hace que el contenedor permanezca vivo indefinidamente, lo que permite la ejecución de comandos dentro del contenedor.
CMD ["sleep", "infinity"]




# docker build --tag image-2b-debian-11-bullseye:2b -f Dockerfile.2b-debian-11-bullseye .
# docker history -H image-2b-debian-11-bullseye:2b --no-trunc

# docker run --name 2b-debian-11-bullseye image-2b-debian-11-bullseye:2b
# docker exec -ti 2b-debian-11-bullseye bash

# docker rm -f 2b-debian-11-bullseye && docker rmi image-2b-debian-11-bullseye:2b

