ARG IMAGE_NAME="debian:bullseye-20230411"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME
#FROM debian:bullseye-20230411

ENV THIS_IMAGE=${IMAGE_NAME}

# Copia el archivo entrypoint.sh a la imagen
COPY entrypoint.01.sh /usr/local/bin/entrypoint.sh


RUN apt-get update && \
    apt-get install figlet -y && \
    apt-get install neofetch -y  && \
    apt-get install -y mc && \    
    echo "\nPS1='{ \033[01;33m\]$THIS_IMAGE\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ '" >> /root/.bashrc && \
    echo "alias ls='ls --color=auto' \nalias ll='ls -alF' \nalias lk='ls -l'" >> /root/.bashrc &&\
    # Otorga permisos de ejecución al archivo entrypoint.sh
    chmod +x /usr/local/bin/entrypoint.sh 
 




# Define el comando de entrada predeterminado
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
 
# Define el comando predeterminado si no se proporciona ninguno al iniciar el contenedor
CMD ["/bin/bash"] 




# docker build --tag image-2b-debian-11-bullseye:2b -f Dockerfile.2b-debian-11-bullseye .
# docker history -H image-2b-debian-11-bullseye:2b --no-trunc

# docker run --name 2b-debian-11-bullseye image-2b-debian-11-bullseye:2b
# docker exec -ti 2b-debian-11-bullseye bash

# docker rm -f 2b-debian-11-bullseye && docker rmi image-2b-debian-11-bullseye:2b

