FROM debian:bullseye-20230411

# Configurar repositorios históricos de Debian 11
RUN echo 'deb http://archive.debian.org/debian bullseye main' > /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get -o Acquire::Check-Valid-Until=false install -y \
        figlet \
        neofetch \
        mc && \
    rm -rf /var/lib/apt/lists/*

# Copiar entrypoint
COPY entrypoint.01.sh /usr/local/bin/entrypoint.sh

# Configurar prompt, alias y permisos
RUN echo "\nPS1='{ \033[01;33m\]debian:bullseye-20230411\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] $ '" >> /root/.bashrc && \
    echo "alias ls='ls --color=auto' \nalias ll='ls -alF' \nalias lk='ls -l'" >> /root/.bashrc && \
    chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]




# docker build --tag image-2b-debian-11-bullseye:2b -f Dockerfile.2b-debian-11-bullseye .
# docker history -H image-2b-debian-11-bullseye:2b --no-trunc

# docker run --name 2b-debian-11-bullseye image-2b-debian-11-bullseye:2b
# docker exec -ti 2b-debian-11-bullseye bash

# docker rm -f 2b-debian-11-bullseye && docker rmi image-2b-debian-11-bullseye:2b

