ARG IMAGE_NAME="ubuntu:26.04"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME

ENV THIS_IMAGE=${IMAGE_NAME}

# Copiar script de entrypoint
COPY entrypoint.02.sh /usr/local/bin/entrypoint.sh

# Actualizar e instalar paquetes directamente
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	figlet \
	fastfetch \
	mc && \
	rm -rf /var/lib/apt/lists/* && \
	echo "\nPS1='{ \[\033[01;33m\]\$THIS_IMAGE\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ '" >> /root/.bashrc && \
	echo "alias ls='ls --color=auto'\nalias ll='ls -alF'\nalias lk='ls -l'" >> /root/.bashrc && \
	chmod +x /usr/local/bin/entrypoint.sh

# Define el comando de entrada predeterminado
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Comando para mantener el contenedor activo
CMD ["sleep", "infinity"]


## ENTRYPOINT
# entrypoint.sh recibe $1 como "sleep"
# entrypoint.sh recibe $2 como "infinity"
# Para que los parámetros pasados desde CMD se ejecuten 
# dentro de tu script entrypoint.sh, 
# el archivo del script suele finalizar con la instrucción exec "$@"




# image-3c-ubuntu-26.04:3c
# 3c-ubuntu-26.04

# docker build --tag image-3c-ubuntu-26.04:3c -f Dockerfile.3c-ubuntu-26.04 .
# docker history -H image-3c-ubuntu-26.04:3c --no-trunc

# docker run --name 3c-ubuntu-26.04 image-3c-ubuntu-26.04:3c 
# docker exec -ti 3c-ubuntu-26.04 bash

# docker rm -f 3c-ubuntu-26.04 && docker rmi image-3c-ubuntu-26.04:3c









