ARG IMAGE_NAME="ubuntu:lunar-20230415"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME
# FROM ubuntu:lunar-20230415

ENV THIS_IMAGE=${IMAGE_NAME}

# Copia el archivo entrypoint.sh a la imagen
COPY entrypoint.01.sh /usr/local/bin/entrypoint.sh

RUN apt-get update && \
    apt-get install figlet -y && \
    apt-get install neofetch -y && \
    apt-get install -y mc && \
    echo "\nPS1='{ \033[01;33m\]$THIS_IMAGE\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ '" >> /root/.bashrc && \
    echo "alias ls='ls --color=auto' \nalias ll='ls -alF' \nalias lk='ls -l'" >> /root/.bashrc &&\
    # Otorga permisos de ejecución al archivo entrypoint.sh
    chmod +x /usr/local/bin/entrypoint.sh 

# Define el comando de entrada predeterminado
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
 
# Define el comando predeterminado si no se proporciona ninguno al iniciar el contenedor
CMD ["/bin/bash"] 



# image-2c-ubuntu-23.04:2c
# 2c-ubuntu-23.04

# docker build --tag image-2c-ubuntu-23.04:2c -f Dockerfile.2c-ubuntu-23.04 .
# docker history -H image-2c-ubuntu-23.04:2c --no-trunc

# docker run --name 2c-ubuntu-23.04 image-2c-ubuntu-23.04:2c 
# docker exec -ti 2c-ubuntu-23.04 bash

# docker rm -f 2c-ubuntu-23.04 && docker rmi image-2c-ubuntu-23.04:2c





