ARG IMAGE_NAME="node:20.5.1-bookworm"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME

# docker pull node:20.5.1-bookworm

EXPOSE 80 443


ENV THIS_IMAGE="${IMAGE_NAME}"
ENV THIS_IMAGE_TAG="09"


## include & Entrypoint & scripts
# COPY resources/09-gulp/ /workdir/
COPY --chmod=0755 entrypoint.09-gulp.sh /usr/local/bin/entrypoint.sh 


RUN apt-get update && \
    apt-get install -y nano mc cron && \
    echo "PS1='{ \033[01;33m\]$IMAGE_NAME\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ '" >> /root/.bashrc && \
    echo "alias ll='ls -alF'" >> /root/.bashrc && \
    echo "alias lk='ls -l'" >> /root/.bashrc && \
    echo $(date +"%Y.%m.%d - %T - Dockerfile Image Build : $IMAGE_NAME")  >> /home/docker.init.log


WORKDIR /workdir

RUN npm init -y && \
    npm install --global gulp-cli && \
    npm install --save-dev gulp && \
    npm install --save-dev gulp-concat gulp-header && \
    npm install --save-dev gulp-rename gulp-sourcemaps && \
    npm install --save-dev gulp-uglify && \
    npm install --save-dev gulp-clean-css && \
    npm install --save-dev gulp-html-minifier2 && \
    npm install --save-dev gulp-replace && \
    npm install --save-dev gulp-insert && \
    npm install --save-dev gulp-remove-empty-lines && \
    npm install --save-dev gulp-trimlines




# Define el comando de entrada predeterminado
# ENTRYPOINT ["/tmp/entrypoint.sh"]



# ENTRYPOINT ["sleep 100000"]

# Define el comando predeterminado si no se proporciona ninguno al iniciar el contenedor
# CMD ["/bin/bash"] 


ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node"]


# --------------------------------------------------------------------------------------------

# 09-image-gulp
# 09-gulp

## build:
# docker build --tag 09-image-gulp -f Dockerfile.09-gulp .
# docker history -H 09-node-gulp --no-trunc

## run:
# docker run --name 09-gulp 09-image-gulp
# docker exec -ti 09-gulp bash
# docker exec -ti 09-gulp sh

## remove container & image:
# docker rm -f 09-gulp && docker rmi 09-node-gulp