# version: '3.9'

services:

    my-01-nginx:
        container_name: 01-nginx
        image: 01-image-nginx
        build:
            context: .
            dockerfile: Dockerfile.01-nginx
        init: true
        volumes:
            - $PWD/vol-01-var-log-nginx:/var/log/nginx
            - $PWD/vol-x-01-nginx-conf.d:/etc/nginx/conf.d
            - $PWD/www:/var/www/test
        ports: 
            - "80:80"       
            - "443:443"     
        restart: unless-stopped
        links:
            - my-02-php-8-fpm
        networks:
            00-net-devel-01:
                ipv4_address: 100.0.0.11


    my-02-php-8-fpm:    ## cuidado: si cambias este nombre debes cambiarlo tambien en "fastcgi_pass"
        container_name: 02-php
        image: 02-image-php
        build:
            context: .
            dockerfile: Dockerfile.02-php
        volumes:
            - $PWD/vol-02-var-log-php:/var/log/php
            - $PWD/www:/var/www/test
        restart: unless-stopped
        networks:
            00-net-devel-01:
                ipv4_address: 100.0.0.12



    devel-node-grunt:
        container_name: 09-node-grunt
        image: 09-image-node-grunt
        build:
            context: .
            dockerfile: Dockerfile.09-node-grunt
        init: true
        volumes:
            - ./sources:/workdir/sources
            - ./www:/workdir/www
            - ./Gruntfile.js:/workdir/Gruntfile.js
            - ./package-lock.json:/workdir/package-lock.json
            - ./package.json:/workdir/package.json
        entrypoint: /tmp/entrypoint.sh
        restart: unless-stopped
        networks:
            00-net-devel-01:
                ipv4_address: 100.0.0.19





networks:
    00-net-devel-01:
        name: 00-net-devel-01
        driver: bridge
        ipam:
            config:
                -   subnet: 100.0.0.0/16
                    gateway: 100.0.0.1



# ------------------------------------------------------------------------------------------------
# docker compose up -d
# docker-compose -f docker-compose.yaml up 
# docker-compose -f docker-compose.yaml down

# nginx         docker exec -ti 01-nginx  bash
# PHP           docker exec -it 02-php bash
# ------------------------------------------------------------------------------------------------


# ------------------------------------------------------------------------------------------------
# docker rmi 01-image-php-7.2.33  09-image-node


