version: "3.9"

services:

  os-1a-alpine:
    container_name: 1a-alpine-3.17
    image: image-1a-alpine-3.17:1a

    #  ( opciones de build: ) 
    #  ( opcion 1 , si pongo un puntito va a buscar un dockerfile )
    # build: .

    #  ( opcion 2 , indicamos el contexto )
    build:
      context: .   #( path )
      dockerfile: Dockerfile.1a-alpine-3.17
    networks:
      - os-nx-linux-network

  os-2a-debian-10-buster:
    container_name: 2a-debian-10-buster
    image: image-2a-debian-10-buster:2a
    build:
      context: .  
      dockerfile: Dockerfile.2a-debian-10-buster
    networks:
      - os-nx-linux-network

  os-2b-debian-11-bullseye:
    container_name: 2b-debian-11-bullseye
    image: image-2b-debian-11-bullseye:2b
    build:
      context: .  
      dockerfile: Dockerfile.2b-debian-11-bullseye
    networks:
      - os-nx-linux-network

  os-2c-ubuntu-23-04:
    container_name: 2c-ubuntu-23.04
    image: image-2c-ubuntu-23.04:2c
    build:
      context: .  
      dockerfile: Dockerfile.2c-ubuntu-23.04
    networks:
      - os-nx-linux-network

  os-3a-centos-7-9-2009:
    container_name: 3a-centos-7.9.2009
    image: image-3a-centos-7.9.2009:3a
    build:
      context: .  
      dockerfile: Dockerfile.3a-centos-7.9.2009
    networks:
      - os-nx-linux-network

  os-4a-redhat-ubi8:
    container_name: 4a-redhat-ubi8
    image: image-4a-redhat-ubi8:4a
    build:
      context: .  
      dockerfile: Dockerfile.4a-redhat-ubi8-8.7
    networks:
      - os-nx-linux-network

  os-4b-fedora-39:
    container_name: 4b-fedora-39
    image: image-4b-fedora-39:4b
    build:
      context: .  
      dockerfile: Dockerfile.4b-fedora-39
    networks:
      - os-nx-linux-network

  os-5c-amazon-linux-2023:
    container_name: 5c-amazon-linux-2023
    image: image-5c-amazon-linux-2023:5c
    build:
      context: .  
      dockerfile: Dockerfile.5c-amazon-linux-2023
    networks:
      - os-nx-linux-network



networks:
  os-nx-linux-network:
    name: os-linux-hub