ARG IMAGE_NAME="node:20.5.1-bookworm"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME

# docker pull node:20.5.1-bookworm

EXPOSE 80 443


ENV THIS_IMAGE="${IMAGE_NAME}"
ENV THIS_IMAGE_TAG="09"


## include & Entrypoint & scripts
# COPY resources/02-php/include /x-include/
COPY --chmod=0755 entrypoint.09-node-webpack.sh /usr/local/bin/entrypoint.sh 


## Para limpiar PHP necesito limpiar php cli
RUN apt-get update && \
    apt-get install -y nano mc cron php-cli && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "PS1='{ \033[01;33m\]$IMAGE_NAME\[\033[00m\] } [\[\033[1;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ '" >> /root/.bashrc && \
    echo "alias ll='ls -alF'" >> /root/.bashrc && \
    echo "alias lk='ls -l'" >> /root/.bashrc && \
    echo $(date +"%Y.%m.%d - %T - Dockerfile Image Build : $IMAGE_NAME")  >> /home/docker.init.log 

WORKDIR /workdir

RUN npm init -y && \
    npm install -g webpack webpack-cli && \
    npm install --save-dev webpack webpack-cli  && \
    npm install --save-dev html-webpack-plugin && \
    npm install --save-dev css-loader && \
    npm install --save-dev style-loader && \
    npm install --save-dev mini-css-extract-plugin && \
    npm install --save-dev css-minimizer-webpack-plugin --save-dev && \
	npm install --save-dev glob webpack-remove-empty-scripts && \
	npm install --save-dev copy-webpack-plugin html-minifier-terser


	
# <-- recién ahora, al final para no barar privilegios necesarios en el contenedor
# USER node 

# Define el comando de entrada predeterminado
# ENTRYPOINT ["/tmp/entrypoint.sh"]
# ENTRYPOINT ["sleep 100000"]
# Define el comando predeterminado si no se proporciona ninguno al iniciar el contenedor
# CMD ["/bin/bash"] 

ENTRYPOINT ["entrypoint.sh"]
CMD ["/bin/bash"] 


# --------------------------------------------------------------------------------------------

# 09-image-node-webpack
# 09-node-webpack

## build:
# docker build --tag 09-image-node-webpack -f Dockerfile.09-node-webpack .
# docker history -H 09-image-node-webpack --no-trunc

## run:
# docker run --name 09-node-webpack 09-image-node-webpack
# docker exec -ti 09-node-webpack bash
# docker exec -ti 09-node-webpack sh

## remove container & image:
# docker rm -f 09-node-webpack && docker rmi 09-image-node-webpack